poetry.lock, pyproject.toml
=> chore: Install dev dependencies

rdfproxy/__init__.py
=> feat: Expose more symbols over package interface

rdfproxy/adapter.py
The enhanced docstring incorporates the description and example from the readme.
=> docs: Add more info and example to SPARQLModelAdapter docstring

README.md
=> docs: Add basic README

rdfproxy/adapter.py, rdfproxy/utils/_types.py
Remove unused import and superfluous blank line
=> style: Minor changes

poetry.lock, pyproject.toml
hypothesis is not used yet in the tests. If we use it at some point, we
can add it again. Without using it, its only baggage we drag along.
Closes: #53
=> chore(deps): drop hypothesis dependency

tests/data/models.py, tests/test_instantiate_model_from_kwargs.py
=> test: add tests for explicit SPARQL binding allocation

.github/workflows/tests.yaml
=> ci(tests): Run test workflow also on PRs targeting main

tests/data/models/author_array_collection_model.py, tests/data/models/author_work_title_model.py, tests/data/models/grouping_model.py, tests/data/models/nested_grouping_model.py
=> test: use ConfigDict instead of class Config for model configuration

README.md
=> docs(readme): replace wikidata query with VALUES query

pyproject.toml
Also run poetry --lock.
Closes #106 .
=> docs: Add author information to pyproject.toml

rdfproxy/utils/_exceptions.py
=> refactor(exceptions): remove unused exceptions

README.md
=> docs(readme): fix/improve example query

tests/tests_mapper/test_sad_path_mapper_grouped_models.py, tests/unit/test_sad_path_get_bindings_from_query_result.py, tests/unit/test_sad_path_replace_query_select_clause.py
Implement basic sad path tests.
=> test: implement basic sad path testing

README.md, examples/full_static_fastapi_example.py, rdfproxy/mapper.py, rdfproxy/utils/_exceptions.py, rdfproxy/utils/utils.py, tests/data/models/author_array_collection_model.py, tests/data/models/author_work_title_model.py, tests/data/models/grouping_model.py, tests/data/models/nested_grouping_model.py, tests/tests_mapper/test_sad_path_mapper_grouped_models.py
=> feat: field grouping

.github/workflows/publish.yml
=> ci: set up pypi-publish action on release

rdfproxy/sparqlwrapper.py
=> feat: raise HTTP status in SPARQLWrapper.query

.github/workflows/publish.yml, .github/workflows/release-please.yml
Use release-please without PAT and change publish trigger type to "released".
=> ci: fix release-please and publish actions

.github/workflows/deploy-docs.yml, .github/workflows/deptry.yml, .github/workflows/publish.yml, .github/workflows/ruff-formatter.yml, .github/workflows/ruff-linter.yml, .github/workflows/tests.yml, pyproject.toml, rdfproxy/mapper.py, tests/tests_mapper/params/model_bindings_mapper_model_bool_model_union_parameters.py, tests/tests_mapper/params/model_bindings_mapper_parameters.py, tests/tests_mapper/test_model_bindings_mapper.py, tests/tests_sparqlwrapper/test_basic_sparqlwrapper.py, uv.lock
=> fix: handle empty result sets

rdfproxy/adapter.py, rdfproxy/sparqlwrapper.py, tests/tests_sparqlwrapper/test_basic_sparqlwrapper.py, tests/tests_sparqlwrapper/test_sparqlwrapper_model_instantiation.py
=> feat: make SPARQLWrapper/SPARQLModelAdapter asynchronous

docs/reference.md, examples/full_static_fastapi_example.py, rdfproxy/adapter.py, rdfproxy/constructor.py, rdfproxy/utils/checkers/item_checker.py, rdfproxy/utils/exceptions.py, tests/tests_adapter/test_adapter_get_item.py, tests/tests_adapter/test_adapter_grouped_pagination.py, tests/tests_constructor/test_item_query_constructor.py, tests/tests_constructor/test_page_query_constructor.py, tests/tests_constructor/test_query_constructor_items_query.py, tests/unit/tests_checkers/test_get_item_checkers.py
=> feat: implement DetailView feature

rdfproxy/utils/checkers/model_checker.py, rdfproxy/utils/model_utils.py, rdfproxy/utils/utils.py, tests/unit/tests_model_utils/test_model_visitor.py
=> refactor: introduce Visitor class for model checks
