acdh-oeaw/rdfproxy

rdfproxy/adapter.py
rdfproxy/utils/_types.py

fix: Type hint cleanup

---

pyproject.toml

Tests targeting an actual remote endpoint should be marked with a 'remote' marker. Custom markers should be registered, else pytest emits a warning.

chore: Register remote pytest marker in pyproject.toml

---

tests/data/init_model_from_kwargs_parameters.py
tests/data/models.py
tests/test_get_bindings_from_query_result.py
tests/test_instantiate_model_from_kwargs.py
tests/test_sparql_model_adapter.py

Implement basic tests for
- SPARQLModelAdapter,
- get_bindings_from_query_result and
- instantiate_model_from_kwargs.
These basic tests merely aim to initialize the testing suite and are relatively primitive: E.g. just the happy path is targeted and the tests are rather verbose.
closes: #17

test: Implement basic tests

---

rdfproxy/utils/utils.py

The default return format for SPARQLWrapper is XML, yet JSON is required for `get_bindings_from_query_result`. Since the format option cannot be set from an already retrieved QueryResult object and the function depends on JSON results, raise an error if the set result format is not JSON.

feat: Check for JSON result format to get_bindings_from_query_result

---

tests/conftest.py

Importing fixtures is a pytest antipattern and causes Ruff to flag F811. See https://github.com/astral-sh/ruff/issues/4046. Defining fixtures globally in conftest.py is the idiomatic way to remedy the problem.

feat: Use conftest.py for global fixture definitions

---

.github/workflows/tests.yaml

Add a test workflow that runs pytest, pytest-cov and the coveralls action.
closes: #18

ci: Add test workflow

---

examples/README.md
examples/basic_fastapi_example.py
examples/releven_person_fastapi_example.py
examples/wikidata_person_fastapi_example.py
poetry.lock
pyproject.toml

Initialize an examples section with three basic examples showing how to target an actual remote endpoint with RDFProxy and serve the results over simple FastAPI routes.
Closes: #58  and #62.

docs(examples): Initialize an examples section

---

tests/test_instantiate_model_from_kwargs.py

model.dict is deprecated, model.model_dump should be used instead, else a warning is emitted.
See https://docs.pydantic.dev/latest/concepts/serialization/#modelmodel_dump.
Closes: #70.

chore(test): Swap deprecated model.dict for model.model_dump

---

rdfproxy/__init__.py
tests/test_get_bindings_from_query_result.py
tests/test_instantiate_model_from_kwargs.py

The public library interface currently only needs to expose SPARQLModelAdapter, SPARQLBinding and Page.

chore: Declutter public library interface

---

rdfproxy/adapter.py
rdfproxy/utils/sparql_utils.py
tests/test_construct_count_query.py

fix: fix group counting

---

rdfproxy/utils/sparql_utils.py
tests/unit/test_replace_query_select_clause.py
tests/utils/_types.py

Fixes #122.
The new regex non-greedily matches everything after "select" and before "where".
`[\s\S]*?`basically means `.*?` but is more general because it also
matches linebreaks without the` re.DOTALL` flag.
See https://docs.python.org/3/library/re.html#re.DOTALL.

fix: correct regex pattern for SELECT clause extraction

---

rdfproxy/adapter.py
rdfproxy/utils/_types.py
rdfproxy/utils/sparql_utils.py
tests/tests_adapter/test_adapter_grouped_pagination.py

feat: implement pagination behavior for grouped models

---

rdfproxy/utils/_exceptions.py
rdfproxy/utils/sparql_utils.py

The regex with an absolute anchor + negated char set is more precise than the original version. Also, indentation is completely unnecessary, a potential source of bugs and clutters up the implementation.

refactor: implement inject_subquery with re.search and str slicing

---

rdfproxy/utils/sparql_utils.py
tests/unit/test_inject_subquery.py

lupl: fix inject subquery prefix

---

README.md
examples/full_static_fastapi_example.py
examples/releven_person_fastapi_example.py
examples/wikidata_grouped_person_fastapi_example.py
examples/wikidata_ungrouped_person_fastapi_example.py
rdfproxy/__init__.py
rdfproxy/adapter.py
rdfproxy/utils/models.py
tests/tests_adapter/test_adapter_grouped_pagination.py

feat: query parameter model

---

rdfproxy/utils/sparql_utils.py
tests/data/models/dummy_model.py
tests/tests_adapter/test_adapter_grouped_pagination.py

fix: resolve group_by config values for SPARQL binding aliases

---

README.md
examples/full_static_fastapi_example.py
examples/wikidata_grouped_person_fastapi_example.py
rdfproxy/__init__.py
rdfproxy/utils/_types.py
tests/data/models/author_array_collection_model.py
tests/data/models/author_work_title_model.py
tests/data/models/dummy_model.py
tests/data/models/grouping_model.py
tests/data/models/nested_grouping_model.py
tests/data/parameters/model_bindings_mapper_model_bool_parameters.py
tests/tests_adapter/test_adapter_grouped_pagination.py
tests/tests_mapper/test_sad_path_mapper_grouped_models.py

feat: implement rdfproxy.ConfigDict for model config

---

poetry.lock
pyproject.toml
rdfproxy/__init__.py
rdfproxy/adapter.py
rdfproxy/sparql_strategies.py

feat: query strategies

---

rdfproxy/adapter.py

As pointed out by @b1rger in https://github.com/acdh-oeaw/rdfproxy/pull/188, % format specifiers should be used instead of f-strings in log messages.
Closes #196.

fix(logging): use % format specifier for logging

---

rdfproxy/adapter.py
rdfproxy/constructor.py
rdfproxy/utils/_exceptions.py
rdfproxy/utils/_types.py
rdfproxy/utils/checkers/query_checker.py
tests/tests_adapter/test_adapter_check_query_sad_path.py
tests/tests_constructor/test_query_constructor_items_query.py
tests/unit/tests_checkers/test_query_checker.py

The change introduces a `check_query` callable which runs an extensible compose pipeline of query checkers against a given SPARQL query. The `check_query` function runs in `SPARQLModelAdapter` to enable fast failures on inapplicable queries.
Closes #116.

feat: implement query checking

---

.github/workflows/deploy-docs.yml
docs/reference.md

The MkDocs workflow failed because I made `_QueryConstructor` private and didn't update the mkdocs reference generator.
This PR fixes the issue and also adapts the workflow to build on push to any branch, but deploy only on push to main.

fix: reference private _QueryConstructor correctly in mkdocs

---

.pre-commit-config.yaml
rdfproxy/adapter.py
rdfproxy/mapper.py
rdfproxy/utils/_exceptions.py
rdfproxy/utils/_typing.py
rdfproxy/utils/checkers/model_checker.py
rdfproxy/utils/mapper_utils.py
rdfproxy/utils/model_utils.py
tests/unit/tests_checkers/test_model_checker.py
tests/unit/tests_model_utils/test_model_traverse.py

feat: implement RDFProxy-compliance checkers for models

---

examples/full_static_fastapi_example.py

Bindings derived from SPARQL JSON responses feature type-casting according to rdflib.Literal.toPython now; this means that model field definitions must reflect this enhanced typing.
The change specifies more exact types in the
full_static_model_fastapi_example models which currently rightfully raise pydantic ValidationErrors.

fix: adapt types in full_static_model_fastapi_example.py

---

rdfproxy/mapper.py
tests/tests_mapper/test_model_bindings_mapper_none_grouping.py
tests/tests_mapper/test_model_bindings_mapper_none_grouping_issue.py

The change fixes a bug where pd.DataFrame.groupby would drop rows with None keys due to the default dropna=True, causing empty model outputs or triggering an AssertionError in recursive grouping scenarios.
Setting dropna=False explicitly in _instantiate_models allows to preserve None-valued keys during grouping.
Also, the ternary logic in _instantiate_grouped_model_from_df needs to check against an object sentinel instead of None, because None can be a valid SPARQL binding value.
Closes #262.

fix: handle None-valued group keys correctly in mapper aggregation

---

rdfproxy/adapter.py
rdfproxy/utils/checkers/_model_checks.py

Filters for warnings are meant to be controlled by client code and should not be defined in a library.
Also, stacklevel=2 should be set for warnings.warn so that *calling* code gets referenced in warnings, not *called* code.
A better solution for this would be skip_file_prefixes available with 3.12; see https://docs.python.org/3/library/warnings.html#warnings.warn.
Closes #293 .

fix: remove warnings filters and add stacklevel=2
